const HEBREW_TO_ENGLISH_SUPPLEMENT = {} as const;

const localitiesEnUpdated = {
  'אבו גוש': 'Abu Ghosh',
  'אבו סנאן': 'Abu Sinan',
  'אבו קרינאת': 'Abu Krinat',
  'אבו תלול': 'Abu Talul',
  'אבטליון': 'Avtaliyon',
  'אביאל': 'Aviel',
  'אביבים': 'Avivim',
  'אביגדור': 'Avigdor',
  'אביגיל': 'Avigail',
  'אביחיל': 'Avichail',
  'אביעזר': 'Aviezer',
  'אבירים': 'Avirim',
  'אביתר': 'Avitar',
  'אבן יהודה': 'Even Yehuda',
  'אבן מנחם': 'Even Menachem',
  'אבן ספיר': 'Even Sapir',
  'אבן שמואל': 'Even Shmuel',
  'אבני איתן': 'Avni Eitan',
  'אבני חפץ': 'Avni Hafetz',
  'אבנת': 'Avnat',
  'אבשלום': 'Avshalom',
  'אדורה': 'Adora',
  'אדורים': 'Adorim',
  'אדמית': 'Adamit',
  'אדרת': 'Aderet',
  'אודים': 'Odim',
  'אודם': 'Odem',
  'אום אל פחם': 'Umm al-Fahm',
  'אום אל קוטוף': 'Umm al-Qutuf',
  'אום בטין': 'Umm Batin',
  'אופקים': 'Ofakim',
  'אור הגנוז': 'Or HaGanuz',
  'אור הנר': 'Or HaNer',
  'אור יהודה': 'Or Yehuda',
  'אור עקיבא': 'Or Akiva',
  'אורה': 'Ora',
  'אורות': 'Orot',
  'אורטל': 'Ortal',
  'אורים': 'Urim',
  'אורנים': 'Oranim',
  'אורנית': 'Oranit',
  'אושה': 'Usha',
  'אזור': 'Azor',
  'אזור תעשייה אלון התבור': 'Alon Tavor Industrial Zone',
  'אזור תעשייה אפק ולב הארץ': 'Afeq and Lev HaAretz Industrial Zone',
  'אזור תעשייה אריאל': 'Ariel Industrial Zone',
  'אזור תעשייה באר טוביה': 'Be’er Tuvia Industrial Zone',
  'אזור תעשייה בני יהודה': 'Bnei Yehuda Industrial Zone',
  'אזור תעשייה בר-לב': 'Bar-Lev Industrial Zone',
  'אזור תעשייה בראון': 'Brown Industrial Zone',
  'אזור תעשייה ברוש': 'Brosh Industrial Zone',
  'אזור תעשייה ברקן': 'Barkan Industrial Zone',
  'אזור תעשייה גדרה': 'Gedera Industrial Zone',
  'אזור תעשייה דימונה': 'Dimona Industrial Zone',
  'אזור תעשייה הדרומי אשקלון': 'Southern Ashkelon Industrial Zone',
  'אזור תעשייה הר טוב - צרעה': 'Har Tuv - Tzora Industrial Zone',
  'אזור תעשייה חבל מודיעין שוהם': 'Hevel Modi’in - Shoham Industrial Zone',
  'אזור תעשייה יקנעם עילית': 'Yokneam Illit Industrial Zone',
  'אזור תעשייה כנות': 'Kannot Industrial Zone',
  'אזור תעשייה כפר יונה': 'Kfar Yona Industrial Zone',
  'אזור תעשייה כרמיאל': 'Karmiel Industrial Zone',
  'אזור תעשייה מבוא כרמל': 'Mavo Carmel Industrial Zone',
  'אזור תעשייה מבואות הגלבוע': 'Mevo’ot HaGilboa Industrial Zone',
  'אזור תעשייה מישור אדומים': 'Mishor Adumim Industrial Zone',
  'אזור תעשייה מיתרים': 'Meitarim Industrial Zone',
  'אזור תעשייה נ.ע.מ': 'Na’am Industrial Zone',
  'אזור תעשייה ניר עציון': 'Nir Etzion Industrial Zone',
  'אזור תעשייה נשר - רמלה': 'Nesher - Ramla Industrial Zone',
  'אזור תעשייה עד הלום': 'Ad Halom Industrial Zone',
  'אזור תעשייה עידן הנגב': 'Idan HaNegev Industrial Zone',
  'אזור תעשייה עמק חפר': 'Emek Hefer Industrial Zone',
  'אזור תעשייה צ.ח.ר': 'Tz.H.R. Industrial Zone',
  'אזור תעשייה ציפורית': 'Tziporit Industrial Zone',
  'אזור תעשייה צפוני אשקלון': 'Northern Ashkelon Industrial Zone',
  'אזור תעשייה קדמת גליל': 'Kidmat Galil Industrial Zone',
  'אזור תעשייה קיסריה': 'Caesarea Industrial Zone',
  'אזור תעשייה קריית ביאליק': 'Kiryat Bialik Industrial Zone',
  'אזור תעשייה קריית גת': 'Kiryat Gat Industrial Zone',
  'אזור תעשייה רבדים': 'Revadim Industrial Zone',
  'אזור תעשייה רותם': 'Rotem Industrial Zone',
  'אזור תעשייה רמת דלתון': 'Ramat Dalton Industrial Zone',
  'אזור תעשייה שחורת': 'Shahoret Industrial Zone',
  'אזור תעשייה שחק': 'Shahak Industrial Zone',
  'אזור תעשייה שער בנימין': 'Sha’ar Binyamin Industrial Zone',
  'אזור תעשייה שער נעמן': 'Sha’ar Na’aman Industrial Zone',
  'אזור תעשייה תימורים': 'Timorim Industrial Zone',
  'אזור תעשייה תרדיון': 'Tardion Industrial Zone',
  'אחווה': 'Ahva',
  'אחוזם': 'Ahozam',
  'אחוזת ברק': 'Ahuzat Barak',
  'אחיה': 'Ahiya',
  'אחיהוד': 'Ahihud',
  'אחיטוב': 'Ahituv',
  'אחיסמך': 'Ahisamakh',
  'אחיעזר': 'Ahiezer',
  'איבטין': 'Ibtin',
  'איבי הנחל': 'Abei HaNahal',
  'איזור תעשייה מילואות צפון': 'Miluot North Industrial Zone',
  'אייל': 'Eyal',
  'איילת השחר': 'Ayelet HaShahar',
  'איירפורט סיטי': 'Airport City',
  'אילון': 'Eilon',
  'אילות': 'Eilot',
  'אילניה': 'Ilaniya',
  'אילת': 'Eilat',
  'אירוס': 'Irus',
  'איתמר': 'Itamar',
  'איתן': 'Eitan',
  'אכסאל': 'Iksal',
  'אל סייד': 'al-Sayyid',
  'אל עזי': 'al-Azzi',
  'אל עמארני, אל מסק': 'al-Amarani, al-Mask',
  'אל עריאן': 'al-Aryan',
  'אל פורעה': 'al-Fura’a',
  'אל רום': 'El Rom',
  'אלומה': 'Aluma',
  'אלומות': 'Alumot',
  'אלון': 'Alon',
  'אלון הגליל': 'Alon HaGalil',
  'אלון מורה': 'Alon Moreh',
  'אלון שבות': 'Alon Shvut',
  'אלוני אבא': 'Alonei Abba',
  'אלוני הבשן': 'Alonei HaBashan',
  'אלוני יצחק': 'Alonei Yitzhak',
  'אלונים': 'Alonim',
  'אלי עד': 'Eli Ad',
  'אליאב': 'Eliav',
  'אליכין': 'Elyakhin',
  'אליפז ומכרות תמנע': 'Elifaz and Timna Mines',
  'אליפלט': 'Elifelet',
  'אליקים': 'Eliakim',
  'אלישיב': 'Elishiv',
  'אלישמע': 'Elishama',
  'אלמגור': 'Almagor',
  'אלמוג': 'Almog',
  'אלעזר': 'Elazar',
  'אלפי מנשה': 'Alfei Menashe',
  'אלקוש': 'Elkosh',
  'אלקנה': 'Elkana',
  'אמונים': 'Emunim',
  'אמירים': 'Amirim',
  'אמנון': 'Amnon',
  'אמץ': 'Amatz',
  'אניעם': 'Aniam',
  'אעבלין': 'Ibillin',
  'אעירה השחר': 'A’ira HaShahar',
  'אפיק': 'Afik',
  'אפיקים': 'Afikim',
  'אפק': 'Afeq',
  'אפקה': 'Afeka',
  'אפרת': 'Efrat',
  'ארבל': 'Arbel',
  'ארגמן': 'Argaman',
  'ארז': 'Erez',
  'אריאל': 'Ariel',
  'ארסוף': 'Arsuf',
  'אש קודש': 'Esh Kodesh',
  'אשבול': 'Eshbol',
  'אשבל': 'Eshbal',
  'אשדוד': 'Ashdod',
  'אשדוד - א,ב,ד,ה': 'Ashdvd - A,b,d,h',
  'אשדוד - איזור תעשייה צפוני': 'Ashdvd - Ayzvr T’shyyh Tzpvny',
  'אשדוד - ג,ו,ז': 'Ashdvd - G,v,z',
  'אשדוד - ח,ט,י,יג,יד,טז': 'Ashdvd - H,t,y,yg,yd,tz',
  'אשדוד -יא,יב,טו,יז,מרינה,סיטי': 'Ashdvd -ya,yb,tv,yz,mrynh,syty',
  'אשדות יעקב': 'Ashdot Ya’akov',
  'אשחר': 'Ashhar',
  'אשכול': 'Eshkol Regional Council',
  'אשכולות': 'Eshkolot',
  'אשל הנשיא': 'Eshel HaNasi',
  'אשלים': 'Ashalim',
  'אשקלון': 'Ashkelon',
  'אשקלון - דרום': 'Ashkelon - South',
  'אשקלון - צפון': 'Ashkelon - North',
  'אשרת': 'Asherat',
  'אשתאול': 'Eshtaol',
  'אשתמוע': 'Eshtemoa',
  'אתר דודאים': 'Dodaim Site',
  'אתר ההנצחה גולני': 'Golani Memorial Site',
  'באקה אל גרבייה': 'Baqa al-Gharbiyye',
  'באר אורה': 'Be’er Ora',
  'באר גנים': 'Be’er Ganim',
  'באר טוביה': 'Be’er Tuvia',
  'באר יעקב': 'Be’er Ya’akov',
  'באר מילכה': 'Be’er Milka',
  'באר שבע': 'Beersheba',
  'באר שבע - דרום': 'Beersheba - South',
  'באר שבע - מזרח': 'Beersheba - East',
  'באר שבע - מערב': 'Beersheba - West',
  'באר שבע - צפון': 'Beersheba - North',
  'בארות יצחק': 'Be’erot Yitzhak',
  'בארותיים': 'Be’erotayim',
  'בארי': 'Be’eri',
  'בוסתן הגליל': 'Bustan HaGalil',
  'בוקעתא': 'Buq’ata',
  'בורגתה': 'Burgata',
  'בחן': 'Bahan',
  'בטחה': 'Bitha',
  'בי"ס כרמים בנימינה': 'Kramim School, Binyamina',
  'ביצרון': 'Bitzaron',
  'ביר אלמכסור': 'Bir al-Maksur',
  'ביריה': 'Biriya',
  'בית אורן': 'Beit Oren',
  'בית אל': 'Beit El',
  'בית אלעזרי': 'Beit Elazari',
  'בית אלפא וחפציבה': 'Beit Alfa and Hefziba',
  'בית אריה': 'Beit Aryeh',
  'בית ברל': 'Beit Berl',
  'בית גוברין': 'Beit Guvrin',
  'בית גמליאל': 'Beit Gamliel',
  'בית דגן': 'Beit Dagan',
  'בית הברכה': 'Beit HaBracha',
  'בית הגדי': 'Beit HaGadi',
  'בית הלוי': 'Beit HaLevi',
  'בית הלל': 'Beit Hillel',
  'בית העלמין החדש נהריה': 'New Cemetery Nahariya',
  'בית העלמין החדש עכו': 'New Cemetery Acre',
  'בית העמק': 'Beit HaEmek',
  'בית הערבה': 'Beit HaArava',
  'בית השיטה': 'Beit HaShita',
  'בית זית': 'Beit Zeit',
  'בית זרע': 'Beit Zera',
  'בית חג\\"י': 'Byt Hgy',
  'בית חגלה': 'Beit Hogla',
  'בית חורון': 'Beit Horon',
  'בית חלקיה': 'Beit Helkia',
  'בית חנן': 'Beit Hanan',
  'בית חנניה': 'Beit Hanania',
  'בית חרות': 'Beit Herut',
  'בית חשמונאי': 'Beit Hashmonai',
  'בית יהושע': 'Beit Yehoshua',
  'בית יוסף': 'Beit Yosef',
  'בית ינאי': 'Beit Yannai',
  'בית יצחק - שער חפר': 'Beit Yitzhak - Sha’ar Hefer',
  'בית ירח': 'Beit Yerah',
  'בית יתיר': 'Beit Yatir',
  'בית לחם הגלילית': 'Beit Lehem HaGlilit',
  'בית מאיר': 'Beit Meir',
  'בית נחמיה': 'Beit Nehemia',
  'בית ניר': 'Beit Nir',
  'בית נקופה': 'Beit Nekofa',
  'בית סוהר צלמון': 'Tzalmon Prison',
  'בית סוהר קישון': 'Kishon Prison',
  'בית ספר שדה מירון': 'Meron Field School',
  'בית עובד': 'Beit Oved',
  'בית עוזיאל': 'Beit Uziel',
  'בית עזרא': 'Beit Ezra',
  'בית עלמין מורשה': 'Moresha Cemetery',
  'בית עלמין תל רגב': 'Tel Regev Cemetery',
  'בית עריף': 'Beit Arif',
  'בית צבי': 'Beit Tzvi',
  'בית קמה': 'Beit Kama',
  'בית קשת': 'Beit Keshet',
  'בית רימון': 'Beit Rimon',
  'בית שאן': 'Beit She’an',
  'בית שמש': 'Beit Shemesh',
  'בית שערים': 'Beit She’arim',
  'בית שקמה': 'Beit Shikma',
  'ביתן אהרן': 'Beitan Aharon',
  'ביתר עילית': 'Beitar Illit',
  'בלפוריה': 'Balfouria',
  'בן זכאי': 'Ben Zakkai',
  'בן עמי': 'Ben Ami',
  'בן שמן': 'Ben Shemen',
  'בני אדם': 'Bnei Adam',
  'בני ברק': 'Bnei Brak',
  'בני דקלים': 'Bnei Dekalim',
  'בני דרום': 'Bnei Darom',
  'בני דרור': 'Bnei Dror',
  'בני יהודה וגבעת יואב': 'Bnei Yehuda and Givat Yoav',
  'בני נצרים': 'Bnei Netzarim',
  'בני עטרות': 'Bnei Atarot',
  'בני ציון': 'Bnei Zion',
  'בני ראם': 'Bnei Re’em',
  'בניה': 'Bneia',
  'בנימינה': 'Binyamina',
  'בנימינה גבעת עדה': 'Binyamina-Givat Ada',
  'בסמת טבעון': 'Basmat Tivon',
  'בענה': 'Bi’ina',
  'בצרה': 'Batzra',
  'בצת': 'Betzet',
  'בקוע': 'Beko’a',
  'בקעות': 'Beka’ot',
  'בר גיורא': 'Bar Giora',
  'בר יוחאי': 'Bar Yohai',
  'בר כוכבא': 'Bar Kokhba',
  'ברוכין': 'Bruchin',
  'ברור חיל': 'Berur Hayil',
  'ברוש': 'Brosh',
  'ברטעה': 'Barta’a',
  'ברכיה': 'Barkia',
  'ברעם': 'Bar’am',
  'ברקאי': 'Barkai',
  'ברקן': 'Barkan',
  'ברקת': 'Bareket',
  'בת הדר': 'Bat Hadar',
  'בת חן': 'Bat Hen',
  'בת חפר': 'Bat Hefer',
  'בת ים': 'Bat Yam',
  'בת עין': 'Bat Ayin',
  'בת שלמה': 'Bat Shlomo',
  'בתי מלון ים המלח': 'Dead Sea Hotels',
  'בתרונות': 'Bataronot',
'גאולי תימן': 'Geulei Teiman',
'גאולים': 'Geulim',
'גאליה': 'Gealia',
'גבולות': 'Gvulot',
'גבים, מכללת ספיר': 'Gevim, Sapir College',
'גבע בנימין': "Geva Binyamin",
'גבע כרמל': 'Geva Carmel',
'גבעון החדשה': "Giv'on HaHadasha",
'גבעות': 'Gvaot',
'גבעות בר': 'Gvaot Bar',
'גבעות עדן': 'Gvaot Eden',
'גבעת אבני': "Givat Avni",
'גבעת אלה': "Givat Ela",
'גבעת אסף': "Givat Assaf",
'גבעת ברנר': "Givat Brenner",
'גבעת הראל': "Givat Harel",
'גבעת הרואה': "Givat HaRo'eh",
'גבעת השלושה': "Givat HaShlosha",
'גבעת וולפסון': "Givat Wolfson",
'גבעת וושינגטון': "Givat Washington",
'גבעת חיים איחוד': "Givat חיים Ihud",
'גבעת חיים מאוחד': "Givat Haim Meuhad",
'גבעת חן': "Givat Hen",
'גבעת יערים': "Givat Ye'arim",
'גבעת ישעיהו': "Givat Yeshayahu",
'גבעת עדה': "Givat Ada",
'גבעת עוז': "Givat Oz",
'גבעת פורת יוסף': "Givat Porat Yosef",
'גבעת שמואל': 'Givat Shmuel',
'גבעת שפירא': "Givat Shapira",
'גבעתי': "Givati",
'גבעתיים': 'Givatayim',
'גברעם': "Gevar'am",
'גבת': 'Gvat',
'גדות': 'Gadot',
'גדעונה': "Gid'ona",
'גדרה': 'Gedera',
'גונן': 'Gonen',
'גופנה': 'Gofna',
'גורן': 'Goren',
  'גורנות הגליל': 'Goronot HaGalil',
  'גזית': 'Gzyt',
  'גזר': 'Gzr',
  'גיאה': 'Gyah',
  'גיבתון': 'Gybtvn',
  'גיזו': 'Gyzv',
  'גילת': 'Gylt',
  'גינוסר': 'Gynvsr',
  'גינתון': 'Gyntvn',
  'גן יבנה': 'Gan Yavne',
  'דימונה': 'Dimona',
  'הוד השרון': 'Hod HaSharon',
  'הרצליה': 'Herzliya',
  'הרצליה פיתוח': 'Herzliya Pituach',
  'חדרה': 'Hadera',
  'חולון': 'Holon',
  'חיפה': 'Haifa',
  'טבריה': 'Tiberias',
  'יבנה': 'Yavne',
  'יהוד': 'Yehud',
  'יהוד מונסון': 'Yehud-Monoson',
  'ירושלים': 'Jerusalem',
  'יראון': 'Yir’on',
'כפר ויתקין': 'Kfar Vitkin',
'כפר ורבורג': 'Kfar Warburg',
'כפר ורדים': 'Kfar Vradim',
'כפר זוהרים': 'Kfar Zoharim',
'כפר זיתים': 'Kfar Zeitim',
'כפר חיטים': 'Kfar Hittim',
'כפר חיים': 'Kfar Haim',
'כפר חנניה': 'Kfar Hanania',
'כפר חסידים': 'Kfar Hasidim',
'כפר חרוב': 'Kfar Haruv',
'כפר טרומן': 'Kfar Truman',
'כפר יאסיף': 'Kafr Yasif',
'כפר ידידיה': 'Kfar Yedidia',
'כפר יהושע': 'Kfar Yehoshua',
'כפר יובל': 'Kfar Yuval',
'כפר יונה': 'Kfar Yona',
'כפר יחזקאל': 'Kfar Yehezkel',
'כפר כמא': 'Kfar Kama',
'כפר כנא': 'Kafr Kanna',
'כפר מונש': 'Kfar Monash',
'כפר מימון ותושיה': 'Kfar Maimon VeTushiya',
'כפר מנדא': 'Kafr Manda',
'כפר מנחם': 'Kfar Menahem',
'כפר מסריק': 'Kfar Masaryk',
'כפר מצר': 'Kafr Misr',
'כפר מרדכי': 'Kfar Mordechai',
'כפר נהר הירדן': 'Kfar Nahar HaYarden',
'כפר נוער בן שמן': 'Ben Shemen Youth Village',
'כפר נטר': 'Kfar Netter',
'כפר סאלד': 'Kfar Szold',
'כפר סבא': 'Kfar Saba',
'כפר סילבר': 'Kfar Silver',
'כפר סירקין': 'Kfar Sirkin',
'כפר עבודה': 'Kfar Avoda',
'כפר עזה': 'Kfar Aza',
'כפר עציון': 'Kfar Etzion',
'כפר פינס': 'Kfar Pines',
'כפר קאסם': 'Kafr Qasim',
'כפר קיש': 'Kfar Kish',
'כפר קרע': "Kafr Qara",
'כפר רופין': 'Kfar Ruppin',
'כפר רות': 'Kfar Rut',
'כפר שמאי': 'Kfar Shammai',
'כפר שמואל': 'Kfar Shmuel',
'כפר שמריהו': 'Kfar Shmaryahu',
'כפר תבור': 'Kfar Tavor',
'כפר תפוח': 'Kfar Tapuach',
'כפר תקווה': 'Kfar Tikva',
'כרכום': 'Karkom',
'כרם ביבנה': 'Kerem BeYavne',
'כרם בן זמרה': 'Kerem Ben Zimra',
'כרם רעים': "Kerem Re'im",
'כרם שלום': 'Kerem Shalom',
'כרמי יוסף': 'Karmei Yosef',
'כרמי צור': 'Karmei Tzur',
'כרמי קטיף ואמציה': 'Karmei Katif VeAmatzia',
'כרמיאל': 'Karmiel',
'כרמיה': 'Karmia',
'כרמים': 'Kramim',
'כרמית': 'Karmit',
 'כרמל': 'Carmel',
'לב החולה': 'Lev HaHula',
'לבון': 'Lavon',
'לביא': 'Lavi',
'לבנים': 'Livnim',
'להב': 'Lahav',
'להבות הבשן': 'Lahavot HaBashan',
'להבות חביבה': 'Lahavot Haviva',
'להבים': 'Lehavim',
'לוד': 'Lod',
'לוזית': 'Luzit',
'לוחמי הגטאות': 'Lohamei HaGetaot',
'לוטם וחמדון': 'Lotem VeHemdon',
'לוטן': 'Lotan',
'לטרון': 'Latrun',
'לימן': 'Liman',
'לכיש': 'Lachish',
'לפיד': 'Lapid',
'לפידות': 'Lapidot',
'לקיה': 'Lakiya',
'מאור': 'Maor',
'מאיר שפיה': 'Meir Shfeya',
'מבוא ביתר': 'Mevo Beitar',
'מבוא דותן': 'Mevo Dotan',
'מבוא חורון': 'Mevo Horon',
'מבוא חמה': 'Mevo Hama',
'מבוא מודיעים': "Mevo Modi'im",
'מבואות יריחו': 'Mevoot Yericho',
'מבועים': 'Mabuim',
'מבטחים, עמיעוז, ישע': 'Mivtahim, Amioz, Yesha',
'מבקיעים': 'Mavkiim',
'מבשרת ציון': 'Mevaseret Zion',
'מגדים': 'Magadim',
'מגדל': 'Migdal',
'מגדל העמק': 'Migdal HaEmek',
'מגדל עוז': 'Migdal Oz',
'מגדל תפן': 'Migdal Tefen',
'מגדלים': 'Migdalim',
'מגל': 'Magal',
'מגן': 'Magen',
'מגן שאול': 'Magen Shaul',
'מגרון': 'Migron',
'מגשימים': 'Magshimim',
'מדרך עוז': 'Midrach Oz',
'מדרשת בן גוריון': 'Midreshet Ben-Gurion',
'מודיעין': "Modi'in",
'מודיעין - ישפרו סנטר': "Modi'in - Yishpro Center",
'מודיעין - ליגד סנטר': "Modi'in - Ligad Center",
'מודיעין מכבים רעות': "Modi'in-Maccabim-Re'ut",
'מודיעין עילית': 'Modi’in Illit',
'מודיעין-מכבים-רעות': "Modi'in-Maccabim-Re'ut",
'מולדת': 'Moledet',
'מונוסון': 'Monosson',
'מועאוויה': "Mu'awiya",
'מוצא עילית': 'Motza Illit',
'מוקיבלה': 'Muqeibila',
'מורן': 'Moran',
'מורשת': 'Moreshet',
'מזור': 'Mazor',
'מזכרת בתיה': 'Mazkeret Batya',
'מזרע': 'Mizra',
'מזרעה': "Mazra'a",
'מחולה': 'Mehola',
'מחניים': 'Machanayim',
'מחסיה': 'Mahsia',
'מטווח ניר עם': "Nir Am Firing Range",
'מטולה': 'Metula',
'מטע': 'Mata',
'מי עמי': 'Mi Ami',
'מייסר': 'Meiser',
'מיני ישראל - נחשון': 'Mini Israel - Nachshon',
'מיצד': 'Meitzad',
'מיצר': 'Meitzar',
'מירב': 'Merav',
'מירון': 'Meron',
'מישר': 'Meishar',
'מיתר': 'Meitar',
'מכון וינגייט': 'Wingate Institute',
'מכורה': 'Mekhora',
'מכינת אלישע': 'Elisha Academy',
'מכמורת': 'Michmoret',
'מכמנים - כמאנה מערבית': 'Mikhmanim - Kamanah West',
'מלאכי השלום': 'Malachei HaShalom',
'מלונות ים המלח מרכז': 'Dead Sea Hotels Center',
'מלכיה': 'Malkia',
'מנוחה': 'Menuha',
'מנוף': 'Manof',
'מנות': 'Manot',
'מנחמיה': 'Menahamiya',
'מנחת מחניים': 'Machanayim Airstrip',
'מנרה': 'Manara',
'מנשית זבדה': 'Manshiyat Zabda',
'מסד': 'Masad',
'מסדה': 'Massada',
'מסוף אורנית': 'Oranit Terminal',
'מסילות': 'Mesilot',
'מסילת ציון': 'Mesilat Zion',
'מסלול': 'Maslul',
'מסעדה': "Mas'ade",
'מעברות': "Ma'abarot",
'מעגלים, גבעולים, מלילות': "Ma'agalim, Giv'olim, Melilot",
'מעגן': "Ma'agan",
'מעגן מיכאל': "Ma'agan Michael",
'מעוז חיים': "Ma'oz Haim",
'מעון': "Ma'on",
'מעון צופיה': 'Maon Zofia',
'מעונה': "Me'ona",
'מעיין ברוך': "Ma'ayan Baruch",
'מעיין צבי': "Ma'ayan Zvi",
'מעיליא': "Mi'ilya",
'מעלה אפרים': "Ma'ale Efraim",
'מעלה גלבוע': "Ma'ale Gilboa",
'מעלה גמלא': "Ma'ale Gamla",
'מעלה החמישה': "Ma'ale HaHamisha",
'מעלה חבר': "Ma'ale Hever",
'מעלה לבונה': "Ma'ale Levona",
'מעלה מכמש': "Ma'ale Mikhmas",
'מעלה עירון': "Ma'ale Iron",
'מעלה עמוס': "Ma'ale Amos",
'מעלה צביה': "Ma'ale Tzviya",
'מעלה רחבעם': "Ma'ale Rehavam",
'מעלות תרשיחא': 'Maalot-Tarshiha',
'מענית, גבעת חביבה': "Ma'anit, Givat Haviva",
'מעש': "Ma'as",
'מפלסים': 'Mefalsim',
'מצדה': 'Masada',
'מצובה': 'Mitzuva',
'מצוקי דרגות': 'Metsoke Dragot',
'מצליח': 'Matzliah',
'מצפה': 'Mitzpe',
'מצפה אילן': 'Mitzpe Ilan',
'מצפה דני': 'Mitzpe Danny',
'מצפה זי"ו': 'Mitzpe Ziv',
'מצפה חגית': 'Mitzpe Hagit',
'מצפה יאיר': 'Mitzpe Yair',
'מצפה יריחו': 'Mitzpe Yericho',
'מצפה מדרג': 'Mitzpe Madreg',
'מצפה נטופה': 'Mitzpe Netofa',
'מצפה רמון': 'Mitzpe Ramon',
'מצפה שלם': 'Mitzpe Shalem',
'מצפור פצאל': 'Petzel Lookout',
'מצר': 'Metzer',
'מקווה ישראל': 'Mikve Israel',
'מרגליות': 'Margaliot',
'מרום גולן': 'Merom Golan',
'מרחב עם': 'Merhav Am',
'מרחביה מושב': 'Merhavia Moshav',
'מרחביה קיבוץ': 'Merhavia Kibbutz',
'מרחצאות עין גדי': 'Ein Gedi Spa',
'מרכז אזורי דרום השרון': 'South Sharon Regional Center',
'מרכז אזורי מבואות חרמון': 'Mevoot Hermon Regional Center',
'מרכז אזורי מגילות': 'Megilot Regional Center',
'מרכז אזורי מרום גליל': 'Merom HaGalil Regional Center',
'מרכז אזורי משגב': 'Misgav Regional Center',
'מרכז אזורי רמת כורזים': 'Ramat Korazim Regional Center',
'מרכז חבר': 'Merkaz Hever',
'מרכז שפירא': 'Merkaz Shapira',
'מרעית': "Mar'it",
'משאבי שדה': "Mish'abei Sadeh",
'משגב דב': 'Misgav Dov',
'משגב עם': 'Misgav Am',
'משהד': 'Mashhad',
'משואה': 'Masua',
'משואות יצחק': "Masuot Yitzhak",
'משכיות': 'Maskiot',
'משמר איילון': 'Mishmar Ayalon',
'משמר דוד': 'Mishmar David',
'משמר הירדן': 'Mishmar HaYarden',
'משמר הנגב': 'Mishmar HaNegev',
'משמר העמק': 'Mishmar HaEmek',
'משמר השבעה': 'Mishmar HaShiva',
'משמר השרון': 'Mishmar HaSharon',
  'משמרות': 'Mishmarot',
  'משמרת': 'Mishmeret',
  'משען': 'Mashan',
  'מתחם בני דרום': 'Bnei Darom Complex',
'מתחם גלילות': 'Glilot Complex',
'מתחם סקי גלבוע': 'Gilboa Ski Complex',
'מתחם פי גלילות': 'Pi Glilot Complex',
'מתחם שביל התפוזים': 'Shvil HaTapuzim Complex',
  'מתן': 'Matan',
  'מתת': 'Mattat',
  'מתתיהו': 'Mattityahu',
  'נאות גולן': 'Neot Golan',
  'נאות הכיכר': 'Neot Hakikar',
  'נאות מרדכי': 'Neot Mordechai',
  'נאות סמדר': 'Neot Smadar',
  'נאות קדומים': 'Neot Kdumim',
  'נאעורה': 'Naaorah',
  'נבטים': 'Nevatim',
  'נבי שועייב': 'Nave Shvayib',
  'נגבה': 'Negba',
  'נגוהות': 'Ngohot',
  'נהורה': 'Nahorah',
  'נהלל': 'Nahalal',
  'נהריה': 'Nahariya',
  'נוב': 'Nov',
  'נוגה': 'Noga',
  'נוה איתן': 'Nave Eitan',
  'נווה': 'Nave',
  'נווה אור': 'Nave Or',
  'נווה אילן': 'Nave Ilan',
  'נווה ארז': 'Nave Erez',
  'נווה דניאל': 'Nave Daniel',
  'נווה זוהר': 'Nave Zohar',
  'נווה זיו': 'Nave Ziv',
  'נווה חריף': 'Nave Hrif',
  'נווה ים': 'Nave Yam',
  'נווה ימין': 'Nave Yamin',
  'נווה ירק': 'Nave Yarak',
  'נווה מבטח': 'Nave Mivtach',
  'נווה מיכאל - רוגלית': 'Nave Michael - Roglit',
  'נווה צוף': 'Nave Tzuf',
  'נווה שלום': 'Nave Shalom',
  'נועם': 'Noam',
  'נוף איילון, שעלבים': 'Nof Ayylvn, Shalbyim',
  'נוף הגליל': '  Nof HaGalil',
  'נופי נחמיה': 'Nofi Nehemia',
  'נופי פרת': 'Nofi Part',
  'נופים': 'Nofim',
  'נופית': 'Nofit',
  'נופך': 'Nofach',
  'נוקדים': 'Nokdim',
  'נורדיה': 'Nordiya',
  'נורית': 'Nurit',
  'נחושה': 'Nechusha',
  'נחל עוז': 'Nahal Oz',
  'נחלה': 'Nahalah',
  'נחליאל': 'Nahalael',
  'נחלים': 'Nahalim',
  'נחם': 'Naham',
  'נחף': 'Nahaf',
  'נחשון': 'Nachshon',
  'נחשונים': 'Nachshonim',
  'נטועה': 'Netuah',
  'נטור': 'Natur',
  'נטע': 'Neta',
  'נטעים': 'Netayim',
  'נטף': 'Nataf',
  'נילי': 'Nily',
  'נין': 'Nin',
  'ניצן': 'Nizan',
  'ניצנה': 'Nizanah',
  'ניצני עוז': 'Nizani Oz',
  'ניצנים': 'Nizaniym',
  'ניר אליהו': 'Nir Eliyahu',
  'ניר בנים': 'Nir Banim',
  'ניר גלים': 'Nir Gilim',
  'ניר דוד': 'Nir David',
  'ניר יצחק': 'Nir Yitzhak',
  'ניר ישראל': 'Nir Israel',
  'ניר משה': 'Nir Moshe',
  'ניר עוז': 'Nir Oz',
  'ניר עם': 'Nir Am',
  'ניר עציון, ימין אורד': 'Nir Etzion, Yemin Ored',
  'ניר עקיבא': 'Nir Akiva',
  'ניר צבי': 'Nir Tzvi',
  'נירים': 'Nirim',
  'נירית': 'Nirit',
  'נמל קיסריה': 'Caesarea Port',
  'נמרוד': 'Nimrod',
  'נס הרים': 'Ness Harim',
  'נס עמים': 'Ness Amim',
  'נס ציונה': 'Ness Tzionah',
  'נעורים': 'Neurim',
  'נעלה': 'Naleh',
  'נעמה': 'Nammah',
  'נען': 'Naan',
  'נערן': 'Naaran',
  'נצר חזני': 'Natzar Hazzani',
  'נצר סרני': 'Natzar Sirni',
  'נצרת': 'Natzeret',
  'נריה': 'Neria',
  'נשר': 'Nesher',
  'נתיב הגדוד': 'Nativ Hagadud',
  'נתיב העשרה': 'Nativ Hashara',
  'נתיב השיירה': 'Nativ Hashyera',
  'נתיבות': 'Netivot',
  'נתניה - מזרח': 'Nataniya - West',
  'נתניה - מערב': 'Nataniya - South',
  'סאסא': 'Sasa',
  'סביון': 'Savyon',
  'סגולה': 'Sgola',
  'סואעד חמירה': 'Soa’ad Hamirah',
  'סולם': 'Solam',
  'סוסיא': 'Sosia',
  'סוסיא הקדומה': 'Sosia Hakduma',
  'סופה': 'Sofa',
  'סכנין': 'Sknyn',
  'עכו': 'Acre',
  'ערד': 'Arad',
  'פרדס חנה כרכור': 'Pardes Hanna-Karkur',
  'פתח תקווה': 'Petah Tikva',
  'צורן': 'Tzoran',
  'צפת': 'Safed',
  'קדימה צורן': 'Kadima-Zoran',
  'קיסריה': 'Caesarea',
  'קריית אונו': 'Kiryat Ono',
  'קריית אתא': 'Kiryat Ata',
  'קריית ביאליק': 'Kiryat Bialik',
  'קריית גת': 'Kiryat Gat',
  'קריית חיים': 'Kiryat Haim',
  'קריית טבעון': 'Kiryat Tivon',
  'קריית ים': 'Kiryat Yam',
  'קריית מוצקין': 'Kiryat Motzkin',
  'קריית מלאכי': 'Kiryat Malakhi',
  'קריית עקרון': 'Kiryat Ekron',
  'קרית שמונה': 'Kiryat Shmona',
  'ראשון לציון': 'Rishon LeZion',
  'רחובות': 'Rehovot',
  'רמלה': 'Ramla',
  'רמת גן': 'Ramat Gan',
  'רמת השרון': 'Ramat HaSharon',
  'רעננה': 'Raanana',
  'שדרות': 'Sderot',
  'שתולה': 'Shtula',
  'תל אביב - דרום העיר ויפו': 'Tel Aviv-Yafo — South & Jaffa',
  'תל אביב - מזרח': 'Tel Aviv-Yafo — East',
  'תל אביב - מרכז העיר': 'Tel Aviv-Yafo — City Center',
  'תל אביב - עבר הירקון': 'Tel Aviv-Yafo — Across the Yarkon',
  'תעוז': 'Ta’oz',
  'אלעד': 'Elad',
  'בועיינה-נוג\'ידאת': 'Bu’eine Nujeidat',
'ביר הדאג\'': "Bir Hadaj",
'בית ג\'אן': "Beit Jann",
'בית חג"י': 'Beit Haggai',
'בני עי"ש': 'Bnei Ayish',
'ג\'דידה מכר': 'Jdeideh-Makr',
'ג\'וליס': 'Julis',
'ג\'לג\'וליה': 'Jaljulia',
'ג\'סר א-זרקא': 'Jisr az-Zarqa',
'ג\'ש - גוש חלב': 'Jish - Gush Halav',
'ג\'ת': 'Jatt',
'גבעת זאב': "Givat Ze'ev",
'גבעת כ"ח': 'Givat Koah',
'גבעת ניל"י': 'Givat Nili',
'גיתה': 'Gitit',
'גיתית': 'Gitit',
'גלאון': "Gal'on",
'גלגל': 'Gilgal',
'גלעד': "Gil'ad",
'גמזו': 'Gimzo',
'גן הדרום': 'Gan HaDarom',
'גן השומרון': 'Gan HaShomron',
'גן חיים': 'Gan Haim',
'גן יאשיה': 'Gan Yoshiya',
'גן נר': 'Gan Ner',
'גן שורק': 'Gan Sorek',
'גן שלמה': 'Gan Shlomo',
'גן שמואל': 'Gan Shmuel',
'גנות': 'Ganot',
'גנות הדר': 'Ganot Hadar',
'גני הדר': 'Ganei Hadar',
'גני חוגה': 'Ganei Huga',
'גני טל': 'Ganei Tal',
'גני יוחנן': 'Ganei Yohanan',
'גני עם': 'Ganei Am',
'גני תקווה': 'Ganei Tikva',
'גניגר': 'Ginegar',
'געש': 'Gaash',
'געתון': "Ga'aton",
'גפן': 'Gefen',
'גרופית': 'Grofit',
'גשור': 'Geshur',
'גשר': 'Gesher',
'גשר הזיו': 'Gesher HaZiv',
'גת': 'Gat',
'גת רימון': 'Gat Rimon',
'דבוריה': 'Daburiyya',
'דביר': 'Dvir',
'דברת': 'Dovrat',
'דגניה א': 'Degania Alef',
'דגניה ב': 'Degania Bet',
'דוב"ב': 'Dovev',
'דולב': 'Dolev',
'דור, נחשולים': 'Dor, Nahsholim',
'דורות': 'Dorot',
'דורות עילית': 'Dorot Illit',
'דחי': 'Dahy',
'דיר אל-אסד': 'Deir al-Asad',
'דיר חנא': 'Deir Hanna',
'דישון': 'Dishon',
'דליה': 'Dalia',
'דלית אל כרמל': 'Daliyat al-Karmel',
'דלתון': 'Dalton',
'דמיידה': 'Dmeide',
'דפנה': 'Dafna',
'דקל': 'Dekel',
'האון': "HaOn",
'הבונים': 'HaBonim',
'הגבעה הצהובה': 'HaGivah HaTzehuba',
'הגושרים': 'HaGoshrim',
'הדר עם': 'Hadar Am',
'הודיה': 'Hodiya',
'הודיות': 'Hodiyot',
'הושעיה': "Hosha'aya",
'הזורעים': 'HaZoreim',
'החווה של אורי כהן': 'Hava Shel Ori Cohen',
'החווה של זוהר': 'Hava Shel Zohar',
'החווה של יאיא': 'Hava Shel Yaya',
'החווה של מנחם': 'Hava Shel Menachem',
'החווה של עשהאל': 'Hava Shel Asael',
'החותרים': 'HaHotrim',
'היוגב': 'HaYogev',
'היישוב היהודי חברון': 'Hebron Jewish Community',
'הילה': 'Hila',
'המעפיל': "HaMa'apil",
'המרכז האקדמי רופין': 'Ruppin Academic Center',
'הסוללים': 'HaSolelim',
'העוגן': "HaOgen",
'הר אדר': 'Har Adar',
'הר ברכה': 'Har Bracha',
'הר גילה': 'Har Gilo',
'הר חלוץ': 'Har Halutz',
'הר עמשא': 'Har Amasa',
'הראל': 'Harel',
'הרדוף': 'Harduf',
'הרצליה - מערב': 'Herzliya - West',
'הרצליה - מרכז וגליל ים': 'Herzliya - Center and Glil Yam',
'הררית יחד': 'Hararit Yahad',
'ואדי אל חמאם': 'Wadi al-Hamam',
'ואדי אל נעם דרום': 'Wadi al-Naam South',
'ורד יריחו': 'Vered Yericho',
'ורדון': 'Verdon',
'זבדיאל': 'Zavdiel',
'זוהר': 'Zohar',
'זיקים': 'Zikim',
'זיתן': 'Zeitan',
'זכרון יעקב': "Zikhron Ya'akov",
'זכריה': 'Zekharia',
'זמר': 'Zemer',
'זמרת, שובה': 'Zimrat, Shuva',
'זנוח': 'Zanoah',
'זרועה': "Zeru'a",
'זרזיר': 'Zarzir',
'זרחיה': 'Zrahia',
'זרעית': 'Zerait',
'חבצלת השרון וצוקי ים': 'Havatzelet HaSharon and Tzukei Yam',
'חג\'אג\'רה': "Hajajre",
'חגור': 'Hagor',
'חגלה': 'Hogla',
'חד נס': 'Had Nes',
'חדיד': 'Hadid',
'חדרה - מזרח': 'Hadera - East',
'חדרה - מערב': 'Hadera - West',
'חדרה - מרכז': 'Hadera - Center',
'חדרה - נווה חיים': 'Hadera - Neve Haim',
'חוות אביה': 'Havat Aviya',
'חוות אביחי': 'Havat Avihai',
'חוות אל נווה': 'Havat El Naveh',
'חוות אלחי': 'Havat Elhai',
'חוות ארץ האיילים': 'Havat Eretz HaAyalim',
'חוות אשכולות': 'Havat Eshkolot',
'חוות בניהו': 'Havat Benayahu',
'חוות גלעד': "Havat Gil'ad",
'חוות גנות': 'Havat Ganot',
'חוות דרומא': 'Havat Droma',
'חוות הרועה העברי': 'Havat HaRoeh HaIvri',
'חוות הרשאש': 'Havat HaRashash',
'חוות חנינא': 'Havat Hanina',
'חוות טואמין': 'Havat Tuamin',
'חוות טליה': 'Havat Talia',
'חוות יאיר': 'Havat Yair',
'חוות יד השומר': 'Havat Yad HaShomer',
'חוות יויו': 'Havat Yoyo',
'חוות ינון': 'Havat Yinon',
'חוות מגדלים': 'Havat Migdalim',
'חוות מגנזי': 'Havat Maganzi',
'חוות מדבר חבר': 'Havat Midbar Hever',
'חוות מור ואברהם': 'Havat Mor VeAvraham',
'חוות מלאכי אברהם': 'Havat Malachei Avraham',
'חוות מלכיאל': 'Havat Malkiel',
'חוות מנחם': 'Havat Menachem',
'חוות מעלה אהוביה': 'Havat Maale Ahuvia',
'חוות מקנה יהודה': 'Havat Mikneh Yehuda',
'חוות מרום שמואל': 'Havat Merom Shmuel',
'חוות נווה צוף': 'Havat Neve Tzuf',
'חוות נוף אב"י': 'Havat Nof Avi',
'חוות נחל שילה': 'Havat Nahal Shilo',
'חוות נחלת אבות': 'Havat Nahalat Avot',
'חוות נחלת צבי': 'Havat Nahalat Zvi',
'חוות עדן': 'Havat Eden',
'חוות עולם חסד': 'Havat Olam Hesed',
'חוות עמיאל': 'Havat Amiel',
'חוות פריאל': 'Havat Priel',
'חוות צאן קדר': 'Havat Tzon Kedar',
'חוות צרידה': 'Havat Tzerida',
'חוות קשואלה': 'Havat Kashuela',
'חוות ראש תאנה': "Havat Rosh Te'ena",
'חוות שדה': 'Havat Sadeh',
'חוות שוביאל': 'Havat Shuviel',
'חוות שחרית': 'Havat Shaharit',
'חוות תלם צפון': 'Havat Telem North',
'חולדה': 'Hulda',
'חולית': 'Holit',
'חולתה': 'Hulata',
'חומש': 'Homesh',
'חוסן': 'Hosen',
'חוסנייה': 'Hussniyya',
'חוף אכזיב': 'Achziv Beach',
'חוף בצת': 'Betzet Beach',
'חוף זיקים': 'Zikim Beach',
'חוף קליה': 'Kalia Beach',
'חופית': 'Hofit',
'חוקוק': 'Hukok',
'חורה': 'Hura',
'חורפיש': 'Hurfeish',
'חורשים': 'Horashim',
'חזון': 'Hazon',
'חיבת ציון': 'Hibat Zion',
'חיננית': 'Hinanit',
'חיפה - בת גלים ק.אליעזר': 'Haifa - Bat Galim, Kiryat Eliezer',
'חיפה - כרמל, הדר ועיר תחתית': 'Haifa - Carmel, Hadar and Downtown',
'חיפה - מערב': 'Haifa - West',
'חיפה - מפרץ': 'Haifa Bay',
'חיפה - נווה שאנן ורמות כרמל': 'Haifa - Neve Shaanan and Ramot Carmel',
'חיפה - קריית חיים ושמואל': 'Haifa - Kiryat Haim and Shmuel',
'חירן': 'Hiran',
'חלץ': 'Heletz',
'חמד': 'Hemed',
'חמדיה': 'Hamadia',
'חמדת': 'Hemdat',
'חמדת ימים': 'Hemdat Yamim',
'חמרה': 'Hamra',
'חמת גדר': 'Hamat Gader',
'חניאל': 'Haniel',
'חניון רעים אנדרטת הנובה': 'Reim Parking - Nova Memorial',
'חניתה': 'Hanita',
'חנתון': 'Hannaton',
'חספין': 'Haspin',
'חפץ חיים': 'Hafetz Haim',
'חצב': 'Hatzav',
'חצבה': 'Hatzeva',
'חצור': 'Hatzor',
'חצור הגלילית': 'Hatzor HaGlilit',
'חצרים': 'Hatzerim',
'חרב לאת': 'Herev LeEt',
'חרוצים': 'Harutzim',
'חרות': 'Herut',
'חריש': 'Harish',
'חרמש': 'Hermesh',
'חרמש דרום': 'Hermesh South',
'חרשה': 'Harasha',
'חרשים': 'Harashim',
'חשמונאים': 'Hashmonaim',
'טובא זנגריה': 'Tuba-Zangariyye',
'טורעאן': 'Turan',
'טייבה': 'Tayibe',
'טייבה בגלבוע': 'Tayibe in Gilboa',
'טירה': 'Tira',
'טירת יהודה': 'Tirat Yehuda',
'טירת כרמל': 'Tirat Carmel',
'טירת צבי': 'Tirat Zvi',
'טל - אל': 'Tal-El',
'טל מנשה': 'Tal Menashe',
'טל שחר': 'Tal Shahar',
'טללים': 'Tlalim',
'טלמון': 'Talmon',
'טמרה': 'Tamra',
'טמרה בגלבוע': 'Tamra in Gilboa',
'טנא עומרים': 'Tene Omarim',
'טפחות': 'Tefahot',
'יבוא דודי': 'Yavo Dodi',
'יבול': 'Yevul',
'יבנאל': "Yavne'el",
'יגור': 'Yagur',
'יגל': 'Yagel',
'יד בנימין': 'Yad Binyamin',
'יד השמונה': 'Yad HaShmona',
'יד חנה': 'Yad Hanna',
'יד מרדכי': 'Yad Mordechai',
'יד נתן': 'Yad Natan',
'יד רמב"ם': 'Yad Rambam',
'יהוד מונוסון': 'Yehud-Monosson',
'יהל': 'Yahel',
'יובלים': 'Yuvalim',
'יודפת': 'Yodfat',
'יונתן': 'Yonatan',
'יושיביה': 'Yoshivia',
'יזרעאל': 'Yizreel',
'יחיעם': 'Yehiam',
'יטבתה': 'Yotvata',
'ייט"ב': 'Yitav',
'יכיני': 'Yakhini',
'ינוב': 'Yanuv',
'ינוח ג\'ת': 'Yanuh-Jat',
'ינון': 'Yinon',
'יסוד המעלה': 'Yesud HaMaala',
'יסודות': 'Yesodot',
'יסעור': 'Yaasur',
'יעבץ, יעף': "Ya'avetz, Ya'af",
'יעד': "Ya'ad",
'יערה': "Ya'ara",
'יפיע': 'Yafia',
'יפית': 'Yafit',
'יפעת': "Yifat",
'יפתח': 'Yiftah',
'יצהר': 'Yitzhar',
'יציץ': 'Yatzitz',
'יקום': 'Yakum',
'יקיר': 'Yakir',
'יקנעם המושבה והזורע': 'Yokneam Moshava and HaZorea',
'יקנעם עילית': 'Yokneam Illit',
'ירדנה': 'Yardena',
'ירוחם': 'Yeruham',
'ירושלים - אזור תעשייה עטרות': 'Jerusalem - Atarot Industrial Zone',
'ירושלים - דרום': 'Jerusalem - South',
'ירושלים - כפר עקב': 'Jerusalem - Kafr Aqab',
'ירושלים - מזרח': 'Jerusalem - East',
'ירושלים - מערב': 'Jerusalem - West',
'ירושלים - מרכז': 'Jerusalem - Center',
'ירושלים - צפון': 'Jerusalem - North',
'ירחיב': 'Yarhiv',
'ירכא': 'Yarka',
'ירקונה': 'Yarkona',
'ישובי אומן': 'Oman Settlements',
'ישובי יעל': 'Yael Settlements',
'ישעי': 'Yishi',
'ישרש': 'Yashresh',
'יתד': 'Yated',
'כאבול': 'Kabul',
'כאוכב אבו אלהיג\'א': 'Kaokab Abu al-Hija',
'כברי': 'Kabri',
'כדורי': 'Kadoorie',
'כוכב השחר': 'Kokhav HaShahar',
'כוכב יאיר - צור יגאל': 'Kokhav Yair - Tzur Yigal',
'כוכב יעקב': "Kokhav Ya'akov",
'כוכב מיכאל': 'Kokhav Michael',
'כורזים ורד הגליל': 'Korazim and Vered HaGalil',
'כחל': 'Kahal',
'כינרת מושבה': 'Kinneret Moshava',
'כינרת קבוצה': 'Kvutzat Kinneret',
'כיסופים': 'Kisufim',
'כישור': 'Kishor',
'כליל': 'Klil',
'כלנית': 'Kalanit',
'כמהין': 'Kmehin',
'כמון - כמאנה מזרחית': 'Kamon - Kamanah East',
'כנות': 'Kannot',
'כנף': 'Kanaf',
'כסייפה': 'Kseife',
'כסלון': 'Kesalon',
'כסרא סמיע': 'Kisra-Sumei',
'כעביה טבאש': 'Kaabiyye-Tabbash',
'כפר אביב': 'Kfar Aviv',
'כפר אדומים': 'Kfar Adumim',
'כפר אוריה': 'Kfar Uria',
'כפר אחים': 'Kfar Ahim',
'כפר אלדד': 'Kfar Eldad',
'כפר ביאליק': 'Kfar Bialik',
'כפר ביל"ו': 'Kfar Bilu',
'כפר בלום': 'Kfar Blum',
'כפר בן נון': 'Kfar Bin Nun',
'כפר ברא': "Kafr Bara",
'כפר ברוך': 'Kfar Barukh',
'כפר גדעון': 'Kfar Gideon',
'כפר גלים': 'Kfar Galim',
'כפר גליקסון': 'Kfar Glikson',
'כפר גלעדי': "Kfar Giladi",
'כפר גמילה מלכישוע': 'Malkishua Rehabilitation Village',
'כפר דניאל': 'Kfar Daniel',
'כפר האורנים': 'Kfar HaOranim',
'כפר החורש': 'Kfar HaHoresh',
'כפר המכבי': 'Kfar HaMaccabi',
'כפר הנגיד': 'Kfar HaNagid',
'כפר הנוער קריית יערים': 'Kiryat Yearim Youth Village',
'כפר הנוקדים': 'Kfar HaNokdim',
'כפר הנשיא': 'Kfar HaNasi',
'כפר הס': 'Kfar Hess',
'כפר הרא"ה': "Kfar HaRo'eh",
'כפר הרי"ף וצומת ראם': 'Kfar HaRif and Reem Junction',
'כפר ח\'וואלד': 'Khawaled',
'כפר חב"ד': 'Kfar Chabad',
'כפר מל"ל': 'Kfar Malal',
'כרם מהר"ל': 'Kerem Maharal',
'מג\'דל כרום': 'Majd al-Krum',
'מג\'דל שמס': 'Majdal Shams',
'מע\'אר': "Bi'ina",
'מעלה אדומים': "Ma'ale Adumim",
'מצפה אבי"ב': 'Mitzpe Aviv',
'מרכז מיר"ב': 'Merkaz Mirav',
'נווה אטי"ב': "Neve Ativ",
'ניר ח"ן': 'Nir Hen',
'נתיב הל"ה': 'Netiv HaLamed-Heh',
'סאג\'ור': 'Sajur',
'סלמה': 'Salama',
'סלעית': "Sela'it",
'סמר': 'Samar',
'סנדלה': 'Sandala',
'סנסנה': 'Sansana',
'סעד': "Sa'ad",
'סעווה': "Sa'wa",
'סער': 'Saar',
'ספיר': 'Sapir',
'ספסופה - כפר חושן': 'Safsufa - Kfar Hoshen',
'סתריה': 'Sitria',
'ע\'ג\'ר': 'Ghajar',
'עבדון': 'Avdon',
'עברון': 'Evron',
'עגור': 'Agur',
'עדי': 'Adi',
'עדי עד': 'Adei Ad',
'עדנים': 'Adanim',
'עוז וגאון': 'Oz VeGaon',
'עוזה': 'Uza',
'עוזייר, רומאנה': 'Uzair, Rummanah',
'עולש': 'Olesh',
'עומר': 'Omer',
'עופר': 'Ofer',
'עופרים': 'Ofarim',
'עוצם': 'Otzem',
'עזוז': 'Azuz',
'עזר': 'Ezer',
'עזריאל': 'Azriel',
'עזריה': 'Azarya',
'עזריקם': 'Azrikam',
'עטרת': 'Ateret',
'עידן': 'Idan',
'עיינות': 'Ayanot',
'עילבון': 'Eilabun',
'עילוט': 'Ilut',
'עין איילה': 'Ein Ayala',
'עין אל אסד': 'Ein al-Asad',
'עין אל סהלה': 'Ein al-Sahala',
'עין בוקק': 'Ein Bokek',
'עין גב': 'Ein Gev',
'עין גדי': 'Ein Gedi',
'עין דור': 'Ein Dor',
'עין הבשור': 'Ein HaBesor',
'עין הוד': 'Ein Hod',
'עין החורש': 'Ein HaHoresh',
'עין המפרץ': 'Ein HaMifratz',
'עין הנצי"ב': 'Ein HaNatziv',
'עין העמק': 'Ein HaEmek',
'עין השופט': 'Ein HaShofet',
'עין השלושה': 'Ein HaShlosha',
'עין ורד': 'Ein Vered',
'עין זיוון': 'Ein Zivan',
'עין חוד': 'Ein Hud',
'עין חצבה': 'Ein Hatzeva',
'עין חרוד, תל יוסף': 'Ein Harod, Tel Yosef',
'עין יהב': 'Ein Yahav',
'עין יעקב': "Ein Ya'akov",
'עין כרמל': 'Ein Carmel',
'עין מאהל': 'Ein Mahil',
'עין נקובא': 'Ein Naqquba',
'עין עירון': 'Ein Iron',
'עין צורים': 'Ein Tzurim',
'עין קנייא': 'Ein Qiniyye',
'עין ראפה': 'Ein Rafa',
'עין שמר': 'Ein Shemer',
'עין שריד': 'Ein Sarid',
'עין תמר': 'Ein Tamar',
'עינות קדם': 'Einot Kedem',
'עינת': 'Einat',
'עכו - אזור תעשייה': 'Acre - Industrial Zone',
'עכו - רמות ים': 'Acre - Ramot Yam',
'עלומים': 'Alumim',
'עלי': 'Eli',
'עלי זהב - לשם': 'Alei Zahav - Leshem',
'עלמה': 'Alma',
'עלמון': 'Almon',
'עמוקה': 'Amuka',
'עמיחי': 'Amihai',
'עמינדב': 'Aminadav',
'עמיעד': 'Amiad',
'עמיקם': 'Amikam',
'עמיר': 'Amir',
'עמנואל': 'Immanuel',
'עמקה': 'Amka',
'ענב': 'Anav',
'עספיא': 'Isfiya',
'עפולה': 'Afula',
'עפרה': 'Ofra',
'עץ אפרים': 'Etz Efraim',
'עצמון - שגב': 'Atzmon - Segev',
'עראבה': 'Arraba',
'ערב אל נעים': 'Arab al-Naim',
'ערב אל עראמשה': 'Arab al-Aramshe',
'ערוגות': 'Arugot',
'ערערה': "Ar'ara",
'ערערה בנגב': "Ar'ara BaNegev",
'עשהאל': 'Asael',
'עשרת': 'Aseret',
'עתלית': 'Atlit',
'עתניאל': 'Otniel',
'פארן': 'Paran',
'פארק אריאל שרון': 'Ariel Sharon Park',
'פארק תעשיות מגדל עוז': 'Migdal Oz Industrial Park',
'פארק תעשיות פלמחים': 'Palmachim Industrial Park',
'פארק תעשייה ראם': 'Reem Industrial Park',
'פדואל': 'Peduel',
'פדויים': 'Peduyim',
'פדיה': 'Pedaya',
'פוריה כפר עבודה': 'Poria - Kfar Avoda',
'פוריה נווה עובד': 'Poria - Neve Oved',
'פוריה עילית': 'Poria Illit',
'פוריידיס': 'Fureidis',
'פורת': 'Porat',
'פטיש': 'Patish',
'פלך': 'Pelekh',
'פלמחים': 'Palmachim',
'פני קדם': 'Pnei Kedem',
'פנימיית עין כרם': 'Ein Kerem Boarding School',
'פסגות': 'Psagot',
'פסוטה': 'Psottah',
'פעמי תש"ז': 'Paamei Tashaz',
'פצאל': "Petza'el",
'פקיעין': 'Pekiin',
'פקיעין החדשה': 'Pekiin HaHadasha',
'פרדסיה': 'Pardesiya',
'פרוד': 'Parod',
'פרי גן': 'Peri Gan',
'פתחיה': 'Ptachya',
'צאלים': 'Tzeelim',
'צבעון': "Tziv'on",
'צובה': 'Tzuba',
'צוחר, אוהד': 'Tzohar, Ohad',
'צומת אלמוג': 'Almog Junction',
'צומת הגוש': 'Gush Junction',
'צופים': 'Tzofim',
'צופית': 'Tzofit',
'צופר': 'Tzofar',
'צוקים': 'Tzukim',
'צור הדסה': 'Tzur Hadassah',
'צור יצחק': 'Tzur Yitzhak',
'צור משה': 'Tzur Moshe',
'צור נתן': 'Tzur Natan',
'צוריאל': 'Tzuriel',
'צורית גילון': 'Tzurit Gilon',
'ציפורי': 'Zippori',
'צלפון': 'Tzalfon',
'צמח': 'Tzemah',
'צפריה': 'Tzafria',
'צפרירים': 'Tzafririm',
'צפת - נוף כנרת': 'Safed - Nof Kinneret',
'צפת - עיר': 'Safed - City',
'צפת - עכברה': 'Safed - Akbara',
'צרופה': 'Tzerufa',
'צרעה': "Tzora'a",
'קבוצת גבע': 'Kvutzat Geva',
'קבוצת יבנה': 'Kvutzat Yavne',
'קדומים': 'Kedumim',
'קדיתא': 'Kadita',
'קדם ערבה': 'Kedem Arava',
'קדמה': 'Kadma',
'קדמת צבי': 'Kidmat Zvi',
'קדר': 'Kedar',
'קדר דרום': 'Kedar South',
'קדרון': 'Kidron',
'קדרים': 'Kadarim',
'קדש ברנע': 'Kadesh Barnea',
'קוממיות': 'Komemiyut',
'קורנית': 'Koranit',
'קטורה': 'Ketura',
'קיבוץ דן': 'Kibbutz Dan',
'קיבוץ מגידו': 'Kibbutz Megiddo',
'קידה': 'Kida',
'קלחים': 'Kelahim',
'קליה': 'Kalia',
'קלנסווה': 'Qalansawwa',
'קלע אלון': 'Kela Alon',
'קסר א-סר': 'Qasr al-Sir',
'קציר': 'Katzir',
'קצרין': 'Katzrin',
'קצרין - אזור תעשייה': 'Katzrin - Industrial Zone',
'קריית גת, כרמי גת': 'Kiryat Gat, Karmi Gat',
'קריית חינוך מרחבים': 'Merhavim Educational Campus',
'קריית טבעון - בית זייד': 'Kiryat Tivon - Beit Zaid',
'קריית יערים': 'Kiryat Yearim',
'קריית נטפים': 'Kiryat Netafim',
'קריית ענבים': 'Kiryat Anavim',
'קריית שמונה': 'Kiryat Shmona',
'קרית ארבע': 'Kiryat Arba',
'קרני שומרון': 'Karnei Shomron',
'קשת': 'Keshet',
'ראמה': 'Rama',
'ראס אל-עין': 'Ras al-Ein',
'ראס עלי': 'Ras Ali',
'ראש הנקרה': 'Rosh HaNikra',
'ראש העין': 'Rosh HaAyin',
'ראש פינה': 'Rosh Pinna',
'ראש צורים': 'Rosh Tzurim',
'ראשון לציון - מזרח': 'Rishon LeZion - East',
'ראשון לציון - מערב': 'Rishon LeZion - West',
'רבבה': 'Revava',
'רבדים': 'Revadim',
'רביבים': 'Revivim',
'רביד': 'Ravid',
'רגבה': 'Regba',
'רגבים': 'Regevim',
'רהט': 'Rahat',
'רווחה': 'Revaha',
'רוויה': 'Revaya',
'רוחמה': 'Ruhama',
'רומת אל הייב': 'Rumat al-Heib',
'רועי': "Ro'i",
'רותם': 'Rotem',
'רחוב': 'Rehov',
'רחלים': 'Rachelim',
'רטורנו - גבעת שמש': 'Retorno - Givat Shemesh',
'ריחאנייה': 'Rehaniya',
'ריחן': 'Reihan',
'ריינה': 'Reineh',
'רימונים': 'Rimonim',
'רינתיה': 'Rinatya',
'רכסים': 'Rekhasim',
'רם און': 'Ram On',
'רמות': 'Ramot',
'רמות השבים': 'Ramot HaShavim',
'רמות מאיר': 'Ramot Meir',
'רמות מנשה': 'Ramot Menashe',
'רמות נפתלי': 'Ramot Naftali',
'רמת גן - מזרח': 'Ramat Gan - East',
'רמת גן - מערב': 'Ramat Gan - West',
'רמת דוד': 'Ramat David',
'רמת הכובש': 'Ramat HaKovesh',
'רמת השופט': 'Ramat HaShofet',
'רמת טראמפ': 'Ramat Trump',
'רמת יוחנן': 'Ramat Yohanan',
'רמת ישי': 'Ramat Yishai',
'רמת מגרון': 'Ramat Migron',
'רמת מגשימים': 'Ramat Magshimim',
'רמת צבי': 'Ramat Zvi',
'רמת רזיאל': 'Ramat Raziel',
'רנן': 'Ranan',
'רעים': 'Reim',
'רקפת': 'Rakefet',
'רשפון': 'Reshefon',
'רשפים, שלוחות, שלפים': 'Reshafim, Shluhot, Shlafim',
'רתמים': 'Retamim',
'שאנטי במדבר': 'Shanti Bamidbar',
'שאר ישוב': "She'ar Yashuv",
'שבות רחל': 'Shvut Rachel',
'שבי דרום': 'Shavei Darom',
'שבי ציון': 'Shavei Zion',
'שבי שומרון': 'Shavei Shomron',
'שגב שלום': 'Segev Shalom',
'שדה אילן': 'Sde Ilan',
'שדה אליהו': 'Sde Eliyahu',
'שדה אליעזר': 'Sde Eliezer',
'שדה אפרים': 'Sde Efraim',
'שדה בועז': 'Sde Boaz',
'שדה בוקר': 'Sde Boker',
'שדה בר': 'Sde Bar',
'שדה דוד': 'Sde David',
'שדה ורבורג': 'Sde Warburg',
'שדה יואב': 'Sde Yoav',
'שדה יעקב': 'Sde Yaakov',
'שדה יצחק': 'Sde Yitzhak',
'שדה משה': 'Sde Moshe',
'שדה נחום': 'Sde Nahum',
'שדה נחמיה': 'Sde Nehemia',
'שדה ניצן': 'Sde Nitzan',
'שדה עוזיהו': 'Sde Uziyahu',
'שדה צבי': 'Sde Zvi',
'שדות ים': 'Sdot Yam',
'שדות מיכה': 'Sdot Micha',
'שדי אברהם': 'Sdei Avraham',
'שדי חמד': 'Sdei Hemed',
'שדי תרומות': 'Sdei Trumot',
'שדמה': 'Shdema',
'שדמות דבורה': 'Shadmot Dvora',
'שדמות מחולה': 'Shadmot Mehola',
'שדרות, איבים': 'Sderot, Ibim',
'שואבה': "Sho'eva",
'שובל': 'Shoval',
'שוהם': 'Shoham',
'שומרה': 'Shomera',
'שומריה': 'Shomriya',
'שוקדה': 'Shokeda',
'שורש': 'Shoresh',
'שורשים': 'Shorashim',
'שושנת העמקים': 'Shoshanat HaAmakim',
'שזור': 'Shezor',
'שחר': 'Shahar',
'שחרות': 'Shaharut',
'שיבולים': 'Shibolim',
'שיבלי אום אלג\'נם': 'Shibli-Umm al-Ghanam',
'שיטים': 'Shittim',
'שייח\' דנון': "Sheikh Danun",
'שילה': 'Shilo',
'שילת': 'Shilat',
'שכניה': 'Shekhanya',
'שלווה': 'Shalva',
'שלומי': 'Shlomi',
'שלומית': 'Shlomit',
'שלומציון': 'Shlomtzion',
'שמיר': 'Shamir',
'שמעה': "Shim'a",
'שמרת': 'Shomrat',
'שמשית': 'Shimshit',
'שני ליבנה': 'Shani Livne',
'שניר': 'Snir',
'שעב': "Sha'ab",
'שעל': "Sha'al",
'שער אפרים': "Sha'ar Efraim",
'שער הגולן': "Sha'ar HaGolan",
'שער העמקים': "Sha'ar HaAmakim",
'שער מנשה': "Sha'ar Menashe",
'שערי תקווה': "Sha'arei Tikva",
'שפיים': 'Shefayim',
'שפיר': 'Shafir',
'שפר': 'Shefer',
'שפרעם': 'Shefa-Amr',
'שקד': 'Shaked',
'שקף': 'Shekef',
'שרונה': 'Sharona',
'שריגים - לי-און': 'Srigim - Li-On',
'שריד': 'Sarid',
'שרשרת': 'Sharsheret',
'שתולים': 'Shtulim',
'תארבין': 'Tarabin',
'תאשור': 'Taashur',
'תדהר': 'Tidhar',
'תובל': 'Tuval',
'תומר': 'Tomer',
'תחנת רכבת כפר ברוך': 'Kfar Barukh Railway Station',
'תחנת רכבת כפר יהושוע': 'Kfar Yehoshua Railway Station',
'תחנת רכבת קריית מלאכי - יואב': 'Kiryat Malakhi - Yoav Railway Station',
'תחנת רכבת ראש העין': 'Rosh HaAyin Railway Station',
'תימורים': 'Timorim',
'תירוש': 'Tirosh',
'תל חי': 'Tel Hai',
'תל יצחק': 'Tel Yitzhak',
'תל מונד': 'Tel Mond',
'תל עדשים': 'Tel Adashim',
'תל ערד': 'Tel Arad',
'תל ציון': 'Tel Zion',
'תל קציר': 'Tel Katzir',
'תל שבע': 'Tel Sheva',
'תל תאומים': 'Tel Teomim',
'תלם': 'Telem',
'תלמי אליהו': 'Talmei Eliyahu',
'תלמי ביל"ו': 'Talmei Bilu',
'תלמי יוסף': 'Talmei Yosef',
'תלמי יחיאל': 'Talmei Yechiel',
'תלמי יפה': 'Talmei Yafe',
'תלמים': 'Tlamim',
'תמרת': 'Timrat',
'תנובות': 'Tnuvot',
'תעשיון צריפין': 'Taasiyon Tzrifin',
'תפרח': 'Tifrah',
'תקומה': 'Tekuma',
'תקוע': "Tekoa",
'תקוע ד\' וה\'': "Tekoa D and H",
'תרום': 'Tarum',
} as const;

export const HEBREW_TO_ENGLISH = { ...HEBREW_TO_ENGLISH_SUPPLEMENT, ...localitiesEnUpdated } as const;
export default HEBREW_TO_ENGLISH;